Repository JeffersonLab/E2SAR, pull requests merged in 2025-03, with the labels that each got.

#95 LB header fix
  src/e2sarDPSegmenter.cpp
  test/mem_tests.cpp
Labels: bug, 0.2.0

#100 Added scripts for running tools using bash in a simplified form.
  scripts/README.md
  scripts/bash-helpers/README.md
  scripts/bash-helpers/e2sar-receiver.sh
  scripts/bash-helpers/e2sar-sender.sh
  scripts/bash-helpers/free-lb.sh
  scripts/bash-helpers/install.sh
  scripts/bash-helpers/meson.build
  scripts/bash-helpers/overview-lb.sh
  scripts/bash-helpers/reserve-lb.sh
  scripts/bash-helpers/status-lb.sh
  scripts/meson.build
Labels: enhancement, 0.1.0

#101 Fixing install script
  scripts/bash-helpers/install.sh
Labels: bug, 0.1.0

#104 Fix Segmenter::sendEvent and add numpy interfaces
  .gitignore
  meson.build
  src/pybind/py_e2sarDP.cpp
  test/py_test/pytest.ini
  test/py_test/test_b2b_DP.py
Labels: bug, enhancement, 0.1.0
